layout_spectrum: 1
name: Matt-Geo
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.6829787
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
  brandColors:
    - '#1B111F'
    - '#302E43'
    - '#D5C9AD'
    - '#617479'
    - '#7A2F40'
typography_spectrum: 0.1574468
