layout_spectrum: 0.5657673
name: Matt-Geo
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.4966273
  lightness: 0.2680851
  saturation: 0
  rhythmicContrast: 1
  brandColors:
    - '#000001'
    - '#F7F7F7'
    - '#302C31'
    - '#888389'
    - '#5C565D'
typography_spectrum: 0.1574468
